import React from 'react';

const data = [
    {
      id_: null,
      scNm: 'creatinne',
      Abrv: 'creat',
      avlb: 'False',
      sctn: 'biochemistry',
      ordr: null,
      AC: 'hyparine',
      smpl: 'blood',
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: 'uree',
      Abrv: 'uree',
      avlb: 'all',
      sctn: 'biochemistry',
      ordr: null,
      AC: 'hyparine',
      smpl: 'blood',
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: 'BILIRUBINE',
      Abrv: 'BIL',
      avlb: 'False',
      sctn: 'biochemistry',
      ordr: null,
      AC: 'hyparine',
      smpl: 'blood',
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: 'ASAT',
      Abrv: 'TGO',
      avlb: 'all',
      sctn: 'biochemistry',
      ordr: null,
      AC: 'hyparine',
      smpl: 'blood',
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: 'ALAT',
      Abrv: 'TGP',
      avlb: 'all',
      sctn: 'biochemistry',
      ordr: null,
      AC: 'hyparine',
      smpl: 'blood',
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: 'CALCIUM',
      Abrv: 'CAL',
      avlb: 'all',
      sctn: 'biochemistry',
      ordr: null,
      AC: 'void',
      smpl: 'blood',
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: 'ALBUMINE',
      Abrv: 'ALB',
      avlb: 'all',
      sctn: 'biochemistry',
      ordr: null,
      AC: 'hyparine',
      smpl: 'blood',
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: 'Phosphore',
      Abrv: 'PHOS',
      avlb: 'False',
      sctn: 'biochemistry',
      ordr: null,
      AC: 'hyparine',
      smpl: 'blood',
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: null,
      Abrv: 'Mg',
      avlb: 'False',
      sctn: 'biochemistry',
      ordr: null,
      AC: 'hyparine',
      smpl: 'blood',
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: null,
      Abrv: 'PAL',
      avlb: 'False',
      sctn: 'biochemistry',
      ordr: null,
      AC: 'hyparine',
      smpl: 'blood',
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: null,
      Abrv: 'Protide',
      avlb: 'False',
      sctn: 'biochemistry',
      ordr: null,
      AC: 'hyparine',
      smpl: 'blood',
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: null,
      Abrv: 'GGT',
      avlb: 'all',
      sctn: 'biochemistry',
      ordr: null,
      AC: null,
      smpl: 'blood',
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: null,
      Abrv: 'Cholesterol_HDL',
      avlb: 'all',
      sctn: 'biochemistry',
      ordr: null,
      AC: null,
      smpl: 'blood',
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: null,
      Abrv: 'Ionogramme',
      avlb: 'all',
      sctn: 'biochemistry',
      ordr: null,
      AC: null,
      smpl: 'blood',
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: null,
      Abrv: 'CHOLESTEROL_LDL',
      avlb: 'all',
      sctn: 'biochemistry',
      ordr: null,
      AC: null,
      smpl: 'blood',
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: null,
      Abrv: 'GLU',
      avlb: 'all',
      sctn: 'biochemistry',
      ordr: null,
      AC: null,
      smpl: 'blood',
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: null,
      Abrv: 'TRG',
      avlb: 'all',
      sctn: 'biochemistry',
      ordr: null,
      AC: null,
      smpl: 'blood',
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: null,
      Abrv: 'Amylase',
      avlb: 'all',
      sctn: 'biochemistry',
      ordr: null,
      AC: null,
      smpl: 'blood',
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: null,
      Abrv: 'Lipase',
      avlb: 'all',
      sctn: 'biochemistry',
      ordr: null,
      AC: null,
      smpl: 'blood',
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: 'Fer Serique',
      Abrv: 'IRON',
      avlb: 'all',
      sctn: 'biochemistry',
      ordr: null,
      AC: null,
      smpl: 'blood',
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: null,
      Abrv: 'LDH',
      avlb: 'all',
      sctn: 'biochemistry',
      ordr: null,
      AC: null,
      smpl: 'blood',
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: null,
      Abrv: 'AU',
      avlb: 'all',
      sctn: 'biochemistry',
      ordr: null,
      AC: null,
      smpl: 'blood',
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: null,
      Abrv: 'CHOL',
      avlb: 'all',
      sctn: 'biochemistry',
      ordr: null,
      AC: 'hyparine',
      smpl: 'blood',
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: null,
      Abrv: 'CPK',
      avlb: 'all',
      sctn: 'biochemistry',
      ordr: null,
      AC: null,
      smpl: null,
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: 'Glycémie Postprandiale',
      Abrv: 'GPP',
      avlb: 'all',
      sctn: 'biochemistry',
      ordr: null,
      AC: 'hyparine',
      smpl: 'blood',
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: 'Cytokine kinase',
      Abrv: 'CK',
      avlb: 'all',
      sctn: 'biochemistry',
      ordr: null,
      AC: 'hyparine',
      smpl: 'blood',
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: null,
      Abrv: 'test',
      avlb: 'all',
      sctn: 'biochemistry',
      ordr: null,
      AC: null,
      smpl: null,
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: null,
      Abrv: 'Ca15,3',
      avlb: 'all',
      sctn: 'hormonology',
      ordr: null,
      AC: 'void',
      smpl: null,
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: null,
      Abrv: 'Ca19,9',
      avlb: 'all',
      sctn: 'hormonology',
      ordr: null,
      AC: 'void',
      smpl: 'blood',
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: null,
      Abrv: 'AFP',
      avlb: 'all',
      sctn: 'hormonology',
      ordr: null,
      AC: 'void',
      smpl: 'blood',
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: null,
      Abrv: 'ACE',
      avlb: 'all',
      sctn: 'hormonology',
      ordr: null,
      AC: 'void',
      smpl: 'blood',
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: null,
      Abrv: 'PSA_T',
      avlb: 'all',
      sctn: 'hormonology',
      ordr: null,
      AC: 'void',
      smpl: 'blood',
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: 'PSA Libre',
      Abrv: 'PSA_L',
      avlb: 'all',
      sctn: 'hormonology',
      ordr: null,
      AC: 'void',
      smpl: 'blood',
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: null,
      Abrv: 'TSH',
      avlb: 'all',
      sctn: 'hormonology',
      ordr: null,
      AC: 'void',
      smpl: 'blood',
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: null,
      Abrv: 'T4',
      avlb: 'all',
      sctn: 'hormonology',
      ordr: null,
      AC: 'void',
      smpl: null,
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: null,
      Abrv: 'ferritine',
      avlb: 'all',
      sctn: 'hormonology',
      ordr: null,
      AC: null,
      smpl: 'blood',
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: 'prolactine',
      Abrv: 'PRL',
      avlb: 'all',
      sctn: 'hormonology',
      ordr: null,
      AC: 'void',
      smpl: 'blood',
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: 'Ca125',
      Abrv: 'Ca125',
      avlb: 'all',
      sctn: 'hormonology',
      ordr: null,
      AC: 'void',
      smpl: 'blood',
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: 'Ft3',
      Abrv: 'Ft3',
      avlb: 'all',
      sctn: 'hormonology',
      ordr: null,
      AC: 'void',
      smpl: 'blood',
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: 'FNS',
      Abrv: 'FNS',
      avlb: 'all',
      sctn: 'hematology',
      ordr: null,
      AC: 'EDTA',
      smpl: 'blood',
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: null,
      Abrv: 'TP',
      avlb: 'all',
      sctn: 'hematology',
      ordr: null,
      AC: 'citrate',
      smpl: 'blood',
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: null,
      Abrv: 'INR',
      avlb: 'all',
      sctn: 'hematology',
      ordr: null,
      AC: 'citrate',
      smpl: 'blood',
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: null,
      Abrv: 'Time',
      avlb: 'False',
      sctn: 'hematology',
      ordr: null,
      AC: null,
      smpl: null,
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: 'vitasse de sédimentation',
      Abrv: 'VS',
      avlb: 'all',
      sctn: 'hematology',
      ordr: null,
      AC: null,
      smpl: null,
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: 'C- reactive protein',
      Abrv: 'CRP',
      avlb: 'all',
      sctn: 'hematology',
      ordr: null,
      AC: 'citrate',
      smpl: null,
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: 'TCK',
      Abrv: 'TCK',
      avlb: 'all',
      sctn: 'hematology',
      ordr: null,
      AC: null,
      smpl: null,
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: null,
      Abrv: 'fibrinogène',
      avlb: 'all',
      sctn: 'hematology',
      ordr: null,
      AC: null,
      smpl: null,
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: null,
      Abrv: 'GS',
      avlb: 'all',
      sctn: 'hematology',
      ordr: null,
      AC: null,
      smpl: null,
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: 'ASLO',
      Abrv: 'ASLO',
      avlb: 'all',
      sctn: 'hematology',
      ordr: null,
      AC: 'void',
      smpl: null,
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: null,
      Abrv: 'TP Corrige',
      avlb: 'all',
      sctn: 'hematology',
      ordr: null,
      AC: null,
      smpl: null,
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: null,
      Abrv: 'FSP',
      avlb: 'all',
      sctn: 'hematology',
      ordr: null,
      AC: null,
      smpl: null,
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: 'HIV',
      Abrv: 'HIV',
      avlb: 'all',
      sctn: 'serology',
      ordr: null,
      AC: 'void',
      smpl: 'blood',
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: 'HCV',
      Abrv: 'HCV',
      avlb: 'all',
      sctn: 'serology',
      ordr: null,
      AC: 'void',
      smpl: 'blood',
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: 'HBS',
      Abrv: 'HBS',
      avlb: 'all',
      sctn: 'serology',
      ordr: null,
      AC: 'void',
      smpl: 'blood',
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: null,
      Abrv: 'TPHA',
      avlb: 'False',
      sctn: 'serology',
      ordr: null,
      AC: 'void',
      smpl: 'blood',
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: 'ECBU',
      Abrv: 'ECBU',
      avlb: 'False',
      sctn: 'bacteriology',
      ordr: null,
      AC: 'citrate',
      smpl: 'urine',
      anly: null,
      prmtrs: null
    },
    {
      id_: null,
      scNm: 'Paludisme',
      Abrv: 'Paludisme',
      avlb: 'False',
      sctn: 'parasitology',
      ordr: null,
      AC: 'hyparine',
      smpl: 'faeces',
      anly: null,
      prmtrs: null
    }
]

export default data;